apiVersion: v2
name: docmost
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.24.1"
dependencies:
  - name: postgresql
    version: "15.5.21"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: valkey
    version: "0.9.3"
    repository: https://valkey.io/valkey-helm/
    condition: postgresql.enabled

